### ISSUE TITLE
No such file or directory error on terminal launch.

### ISSUE THREAD

**Issue by Lewis-Elborn** [monfresh/install-ruby-on-macos#10]
Hey, great script and thanks for sharing. I was pulling my hair out.

I can barely navigate around the terminal but I'm learning. I did attempt a manual installation via your post but wasn't getting anywhere. So I turned to your script.

The script seems to have worked well, though now when I launch the terminal I'm getting the following;

`Last login: Fri Jun 25 18:56:24 on ttys001
/Users/beaniie/.zshrc:source:1: no such file or directory: /opt/homebrew/opt/chruby/share/chruby/chruby.sh
/Users/beaniie/.zshrc:source:2: no such file or directory: /opt/homebrew/opt/chruby/share/chruby/auto.sh
/Users/beaniie/.zshrc:3: command not found: chruby
`

I've attached some files as requested in your post. Can you help figure what's happening here?

[laptop.log](https://github.com/monfresh/install-ruby-on-macos/files/6718058/laptop.log)
<img width="1371" alt="Screenshot 2021-06-25 at 19 09 12" src="https://user-images.githubusercontent.com/84478399/123467894-ef5e5d80-d5e8-11eb-846d-fd8c070736af.png">

**Comment by Lewis-Elborn** [comment]
Further to this, I notice that the terminal in vs code is still using the default version of ruby that shipped with the machine. What would I need to do to see my homebrew versions of ruby within the vs code terminal and use them?

**Comment by Lewis-Elborn** [comment]
Eurika I was able to solve the errors on launch by opening the `.zshrc` file and removing the lines at the top via `open ~/.zshrc`. Still not sure about vs code tho.

**Comment by monfresh** [comment]
Hi. I'm glad you were able to solve the launch errors! Great job figuring it out on your own!

As for VSCode, it could either be because it's not configured to use the same shell as your Terminal (zsh), or because you haven't set a `.ruby-version` file in your project. Read this for the solutions: https://github.com/monfresh/laptop/issues/69#issuecomment-768705734
