### ISSUE TITLE
Failure on Big Sur - Intel Chip Macbook Pro

### ISSUE THREAD

**Issue by lauraannwilliams** [monfresh/install-ruby-on-macos#3]
Fyi I tried on a brand new macbook pro, but sadly it failed.  Attached the full log -  the default gems seem to be the issue

```
installing default gems from lib:   /Users/pengy/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0 (build_info, cache, doc, extensions, gems, specifications)
                                    benchmark 0.1.0
/Users/pengy/src/ruby-2.7.2/lib/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- openssl (LoadError)
	from /Users/pengy/src/ruby-2.7.2/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /Users/pengy/src/ruby-2.7.2/lib/rubygems/specification.rb:2430:in `to_ruby'
	from ./tool/rbinstall.rb:846:in `block (2 levels) in install_default_gem'
	from ./tool/rbinstall.rb:279:in `open_for_install'
	from ./tool/rbinstall.rb:845:in `block in install_default_gem'
	from ./tool/rbinstall.rb:835:in `each'
	from ./tool/rbinstall.rb:835:in `install_default_gem'
	from ./tool/rbinstall.rb:799:in `block in <main>'
	from ./tool/rbinstall.rb:950:in `block in <main>'
	from ./tool/rbinstall.rb:947:in `each'
	from ./tool/rbinstall.rb:947:in `<main>'
make: *** [do-install-all] Error 1
!!! Installation of ruby 2.7.2 failed!
failed
```

[laptop.log](https://github.com/monfresh/install-ruby-on-macos/files/5706010/laptop.log)

**Comment by lauraannwilliams** [comment]
[gdbm.mkmf.log](https://github.com/monfresh/install-ruby-on-macos/files/5706238/gdbm.mkmf.log)
[openssl.mkmf.log](https://github.com/monfresh/install-ruby-on-macos/files/5706239/openssl.mkmf.log)
Attaching two other associated log files
This seems to be a rubyinstall issue

**Comment by monfresh** [comment]
Hi @lauraannwilliams. Thanks for trying my script, and sorry you are running into issues. The `openssl` error towards the end of the log file points to outdated or incomplete command line tools. I'm surprised Homebrew didn't complain about this at the beginning of the script. From the log file, I noticed that you are running an older version of Catalina. There have since been 3 updates. Could you please try going to System Preferences, and then Software Update, and make sure you have the latest Catalina update?

Once that is done, you can verify that you have the latest Catalina update by running this command in the terminal:
```shell
sw_vers
```
You should see this:
```shell
BuildVersion:	19H114
```
Then check if the command line tools are installed by running `brew doctor`. If you don't see any messages related to missing or outdated command line tools, then you should be able to run the script again. Otherwise, follow any instructions that Homebrew prints out, and try again.

Hopefully that resolves the issue.

**Comment by monfresh** [comment]
To double check, in the title of this issue, you said you are on Big Sur. Are you sure about that? According to the log file, you are on Catalina.

**Comment by lauraannwilliams** [comment]
Yep, I was wrong. Updated the ticket

I'll do a software update too - however i seem to have solved this by following the brew caveat instructions.  

```
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

Thanks for responding so fast

**Comment by monfresh** [comment]
Thanks for reporting this. I was able to reproduce this on my machine by uninstalling and reinstalling Ruby. This was a bug or an undocumented change in the latest version of `ruby-install`. More details here if you're interested: https://github.com/postmodern/ruby-install/issues/387

I found a workaround by using the `--with-openssl-dir` flag to specify the Homebrew version of OpenSSL. I updated the script and I verified it's working on my computer.

**Comment by postmodern** [comment]
@monfresh what is the output of `uname -s` and `uname -m`? I am guessing the new package manager detection code which relies on `$os_platform` isn't detecting Apple Silicon.
https://github.com/postmodern/ruby-install/blob/3cb283cb587378f1065bf8de4c8b573a3a111423/share/ruby-install/package_manager.sh#L8-L36

**Comment by monfresh** [comment]
`uname -s` is Darwin and `uname -m` is x86_64. None of the folks who experienced failed Ruby installations with `ruby-install` version 0.8.0 have been on Apple Silicon Macs.
