### ISSUE TITLE
Trouble when ran script

### ISSUE THREAD

**Issue by tienlonghungson** [monfresh/install-ruby-on-macos#4]
Hello.
It's very nice of you to write a script and spread it throughout the community.
However, when I ran your script, I got some trouble that wasn't listed here https://github.com/monfresh/install-ruby-on-macos/wiki/Troubleshooting-Errors.
So please help me to fix it.
Thanks 
[laptop.log](https://github.com/monfresh/install-ruby-on-macos/files/5739063/laptop.log)

**Comment by monfresh** [comment]
Hi. Thanks for trying my script, and sorry it wasn't working. It looks like you previously installed Homebrew on your own, and Homebrew is finding issues with your Homebrew setup. If you look at the log, you'll see a bunch of different issues and suggestions for how to fix them.

The first thing that jumps out is that you are using macOS 10.13, which Homebrew (and Apple) no longer provide support for:

```
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
```
I will update my README to reflect his.

Is there a particular reason why you haven't or can't upgrade to Catalina, or at least Mojave?

The other issue is this:
```
Error: 
  homebrew-core is a shallow clone.
To `brew update`, first run:
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
automatically to avoid repeatedly performing an expensive unshallow operation in
CI systems (which should instead be fixed to not use shallow clones). Sorry for
the inconvenience!
```

This should fix several of the other issues, so let's try this first. Run:
```shell
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
```
Then quit and restart Terminal, then run my script again, and we'll go from there.

**Comment by tienlonghungson** [comment]
I've fixed some trouble, and here is my log file.
[laptop.log](https://github.com/monfresh/install-ruby-on-macos/files/5743964/laptop.log)

**Comment by tienlonghungson** [comment]
The prerequisite to upgrade to at least Mojave is MacBook Pro from mid 2012, but my Mac is early 2011, so I can do nothing about it.
And I am not so sure about this, but since Apple no longer supports High Siera so m homebrew couldn't find the available bottle for ruby-install and automake. I think the script may have to specify the version for ruby-install and automake.
Anyway, please help me fix this.
Thanks again

**Comment by monfresh** [comment]
Hi @tienlonghungson. Unfortunately, Homebrew doesn't make it easy to specify versions of tools. Have you tried installing `ruby-install` and `automake` manually? Maybe it was a glitch that it couldn't find them? Try running `brew install ruby-install`.

If that doesn't work, the only thing I can think of to suggest is to get a used laptop on eBay, Craigslist, or other similar marketplaces.

**Comment by monfresh** [comment]
You can also try building from source like Homebrew suggests, but I have no idea what kind of problems this might cause.
```
brew install --build-from-source ruby-install
brew install --build-from-source automake
```
Another option could be to use Docker.
