### ISSUE TITLE
Error on install: Config scripts and unbrewed files

### ISSUE THREAD

**Issue by sdaviss** [monfresh/install-ruby-on-macos#6]
Hi, Moncef. Thank you for being such a great teacher. 
It's looking like a prior homebrew install may have caused problems? I'm on macOS 11.1 big sur on a MBPro 16inch.

Here is the laptop.log...

`

Welcome to the Ruby installation script!

You should be and up and running with a working Ruby environment in a few minutes.

The following lines are to help me debug any issues:

Current shell: /bin/zsh.

macOS version:
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69

Mac model:
hw.model: MacBookPro16,1

Homebrew already installed. Skipping ...

Verifying the Homebrew installation...
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/user9/opt/anaconda3/bin/icu-config
  /Users/user9/opt/anaconda3/bin/krb5-config
  /Users/user9/opt/anaconda3/bin/freetype-config
  /Users/user9/opt/anaconda3/bin/xslt-config
  /Users/user9/opt/anaconda3/bin/libpng16-config
  /Users/user9/opt/anaconda3/bin/python3.7-config
  /Users/user9/opt/anaconda3/bin/libpng-config
  /Users/user9/opt/anaconda3/bin/xml2-config
  /Users/user9/opt/anaconda3/bin/python3.7m-config
  /Users/user9/opt/anaconda3/bin/gsl-config
  /Users/user9/opt/anaconda3/bin/python3-config
  /Users/user9/opt/anaconda3/bin/curl-config
  /Users/user9/opt/anaconda3/bin/ncursesw6-config
  /Users/user9/opt/anaconda3/bin/pcre-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib
  /usr/local/lib/libtlImageIO.dylib
  /usr/local/lib/libtliadjust50.dylib
  /usr/local/lib/libtliclean30.dylib
  /usr/local/lib/libtlidenoise50.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@3.8

Warning: You are using macOS 11.1.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

Warning: Could not find an SDK that supports macOS 11.1.
You may have have an outdated or incompatible CLT.
Homebrew found the following SDKs in the CLT install:
  10.14
  10.15

Please update CLT or uninstall it if no updates are available.

Your Homebrew installation reported some errors or warnings.
Review the Homebrew messages to see if any action is needed.
Usage: brew list, ls [options] [formula]

List all installed formulae.

If formula is provided, summarise the paths within its current keg.

        --full-name                  Print formulae with fully-qualified names.
                                     If --full-name is not passed, other
                                     options (i.e. -1, -l, -r and -t)
                                     are passed to ls(1) which produces the
                                     actual output.
        --unbrewed                   List files in Homebrew's prefix not
                                     installed by Homebrew.
        --versions                   Show the version number for installed
                                     formulae, or only the specified formulae if
                                     formula are provided.
        --multiple                   Only show formulae with multiple versions
                                     installed.
        --pinned                     Show the versions of pinned formulae, or
                                     only the specified (pinned) formulae if
                                     formula are provided. See also pin,
                                     unpin.
    -1                               Force output to be one entry per line. This
                                     is the default when output is not to a
                                     terminal.
    -l                               List in long format. If the output is to a
                                     terminal, a total sum for all the file
                                     sizes is printed before the long listing.
    -r                               Reverse the order of the sort to list the
                                     oldest entries first.
    -t                               Sort by time modified, listing most
                                     recently modified first.
    -v, --verbose                    Make some output more verbose.
    -d, --debug                      Display any debugging information.
    -h, --help                       Show this message.
Error: invalid option: --formula

Installing chruby, ruby-install, and the latest Ruby...
Error: undefined method `named' for #<OptionParser:0x00007fba3e054150>
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:92:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
failed
`

**Comment by monfresh** [comment]
Hi @sdaviss. As a first step, I would suggest uninstalling and reinstalling the command line tools. Can you try these steps?

Uninstall the CLT:

```sh
sudo rm -rf /Library/Developer/CommandLineTools
```

Install them again:

```sh
xcode-select --install
```

Run my script again:

```sh
cd ~
/usr/bin/env bash install-ruby 2>&1 | tee ~/laptop.log
```

**Comment by sdaviss** [comment]
Hi Moncef. I removed and reinstalled CLT, but running your script again failed, with complaints about macos 11.1, unexpected files, and undefined methods (output pasted below).

Do you have another troubleshooting suggestion?  Maybe something to do with these last lines?...

> Installing chruby, ruby-install, and the latest Ruby...
> Error: undefined method `named' for #<OptionParser:0x00007fe71eaf0480>
> Please report this bug:
>   https://github.com/Homebrew/homebrew-bundle/issues
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:92:in `bundle'
> /usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
> failed

Thanks.

# =====output======
(base) user9@MBPro16 ~ % cd ~
(base) user9@MBPro16 ~ % /usr/bin/env bash install-ruby 2>&1 | tee ~/laptop.log

Welcome to the Ruby installation script!

You should be and up and running with a working Ruby environment in a few minutes.

The following lines are to help me debug any issues:

Current shell: /bin/zsh.

macOS version:
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69

Mac model:
hw.model: MacBookPro16,1

Homebrew already installed. Skipping ...

Verifying the Homebrew installation...
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/user9/opt/anaconda3/bin/icu-config
  /Users/user9/opt/anaconda3/bin/krb5-config
  /Users/user9/opt/anaconda3/bin/freetype-config
  /Users/user9/opt/anaconda3/bin/xslt-config
  /Users/user9/opt/anaconda3/bin/libpng16-config
  /Users/user9/opt/anaconda3/bin/python3.7-config
  /Users/user9/opt/anaconda3/bin/libpng-config
  /Users/user9/opt/anaconda3/bin/xml2-config
  /Users/user9/opt/anaconda3/bin/python3.7m-config
  /Users/user9/opt/anaconda3/bin/gsl-config
  /Users/user9/opt/anaconda3/bin/python3-config
  /Users/user9/opt/anaconda3/bin/curl-config
  /Users/user9/opt/anaconda3/bin/ncursesw6-config
  /Users/user9/opt/anaconda3/bin/pcre-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib
  /usr/local/lib/libtlImageIO.dylib
  /usr/local/lib/libtliadjust50.dylib
  /usr/local/lib/libtliclean30.dylib
  /usr/local/lib/libtlidenoise50.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@3.8

Warning: You are using macOS 11.1.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.


Your Homebrew installation reported some errors or warnings.
Review the Homebrew messages to see if any action is needed.
Usage: brew list, ls [options] [formula]

List all installed formulae.

If formula is provided, summarise the paths within its current keg.

        --full-name                  Print formulae with fully-qualified names.
                                     If --full-name is not passed, other
                                     options (i.e. -1, -l, -r and -t)
                                     are passed to ls(1) which produces the
                                     actual output.
        --unbrewed                   List files in Homebrew's prefix not
                                     installed by Homebrew.
        --versions                   Show the version number for installed
                                     formulae, or only the specified formulae if
                                     formula are provided.
        --multiple                   Only show formulae with multiple versions
                                     installed.
        --pinned                     Show the versions of pinned formulae, or
                                     only the specified (pinned) formulae if
                                     formula are provided. See also pin,
                                     unpin.
    -1                               Force output to be one entry per line. This
                                     is the default when output is not to a
                                     terminal.
    -l                               List in long format. If the output is to a
                                     terminal, a total sum for all the file
                                     sizes is printed before the long listing.
    -r                               Reverse the order of the sort to list the
                                     oldest entries first.
    -t                               Sort by time modified, listing most
                                     recently modified first.
    -v, --verbose                    Make some output more verbose.
    -d, --debug                      Display any debugging information.
    -h, --help                       Show this message.
Error: invalid option: --formula

Installing chruby, ruby-install, and the latest Ruby...
Error: undefined method `named' for #<OptionParser:0x00007fe71eaf0480>
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:92:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
failed

(base) user9@MBPro16 ~ %

**Comment by monfresh** [comment]
It sounds like your Homebrew is out of date. It thinks that 11.1 is a prerelease. I just ran the script without issues in Big Sur 11.1.

Can you try these steps?

1.  Run `brew update`
2. Run `brew upgrade`
3. Run my script again

**Comment by sdaviss** [comment]
"All done!"

You nailed it; updating brew resolved the errors, and your script appears to  have run successfully.
Thanks, Mon!
